[versions]
accompanist = "0.36.0"
accompanist-system-ui-controller = "0.36.0"
agp = "8.12.3"
android-target-sdk = "36"
android-compile-sdk = "36"
android-min-sdk = "26"
androidx-activity-compose = "1.11.0"
androidx-core = "1.17.0"
androidx-lifecycle = "2.10.0"
annotation = "1.9.1"
appcompat = "1.7.1"
application-version-name = "0.14.0"
cloudy = "0.2.7"
coil = "3.3.0"
compose = "1.9.3"
coroutines-core = "1.10.2"
dbus = "3.3.2"
documentfile = "1.1.0"
ffmpeg = "6.0-2"
file-kit = "0.12.0"
gson = "2.13.2"
jaudiotagger = "3.0.1"
jlibnotify = "1.2.3"
kmpalette = "3.1.0"
kotlin = "2.2.21"
kotlinx-serialization = "1.9.0"
koin = "4.1.1"
ksp = "2.3.2"
ktor = "2.3.12"
markdown-renderer = "0.37.0"
media = "1.7.1"
multiplatform-settings = "1.3.0"
nav3-core = "1.0.0"
reorderable = "3.0.0"
room = "2.8.4"
sqlite = "2.6.1"
vlcj = "4.11.0"
media3-exoplayer = "1.8.0"

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-system-ui-controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-system-ui-controller" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3-core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3-core" }

coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }

components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-cloudy = { module = "com.github.skydoves:cloudy", version.ref = "cloudy" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines-core" }
coroutines-core-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines-core" }

dbus = { module = "com.github.hypfvieh:dbus-java", version.ref = "dbus" }

ffmpeg = { module = "com.arthenica:ffmpeg-kit-full", version.ref = "ffmpeg" }
file-kit = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "file-kit" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jaudiotagger = { module = "net.jthink:jaudiotagger", version.ref = "jaudiotagger" }
jlibnotify = { module = "es.blackleg:jlibnotify", version.ref = "jlibnotify" }
kmpalette = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpalette" }

koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negoctiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

markdown-renderer-core = { module ="com.mikepenz:multiplatform-markdown-renderer", version.ref = "markdown-renderer" }
markdown-renderer-m3 = { module ="com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdown-renderer" }

multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }

reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

vlcj = { module  = "uk.co.caprica:vlcj", version.ref = "vlcj"}

androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-sqlite-wrapper = { module = "androidx.room:room-sqlite-wrapper", version.ref = "room" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3-exoplayer" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }

[bundles]
koin = ["koin-compose", "koin-core", "koin-compose-viewmodel", "koin-compose-viewmodel-navigation"]
accompanist = ["accompanist-pager","accompanist-system-ui-controller", "accompanist-pager-indicators"]
androidx = ["androidx-activity-compose", "androidx-lifecycle", "androidx-core", "androidx-annotation", "androidx-appcompat", "androidx-appcompat-resources", "androidx-media"]
ktor = ["ktor-client-cio", "ktor-client-content-negoctiation", "ktor-client-core"]
